### ISSUE TITLE
Scala 2.12 support

### ISSUE THREAD

**Issue by ngthanhtrung** [nulab/scala-oauth2-provider#109]
Hi, do you guys have any plan to support 2.12 soon?

**Comment by rmmeans** [comment]
My guess would be when Play 2.6 ships since they don't support 2.12 in Play 2.5 - otherwise this library really would need split up into three parts - just the core lib, an Akka lib, and a Play lib.

**Comment by tsuyoshizawa** [comment]
Yes, we have the plan. As rmmeans said, I'm going to support Scala 2.12 when Play 2.6 ships.

> this library really would need split up into three parts - just the core lib, an Akka lib, and a Play lib.

I agree with you. We should separate the modules to be able to release each library.
Then, we can release a module supporting Scala 2.12.

**Comment by tsuyoshizawa** [comment]
Supported Scala 2.12 by #115 

I deployed the supported version as SNAPSHOT
https://oss.sonatype.org/content/repositories/snapshots/com/nulab-inc/scala-oauth2-core_2.12/1.2.1-SNAPSHOT/
