### ISSUE TITLE
Consider using scalafmt

### ISSUE THREAD

**Issue by rmmeans** [nulab/scala-oauth2-provider#111]
I'd be curious of your thoughts of adding `scalafmt` (https://olafurpg.github.io/scalafmt/) to this library? It would make it easier to contribute to as code formatting would be consistently applied and even have tests fail if a contribution comes in that is not formatted to the scalafmt settings. 

If you consider it, I might suggest these format settings in the `.scalafmt.conf` file:

```
style = defaultWithAlign
maxColumn = 120
```

**Comment by tsuyoshizawa** [comment]
I know scalafmt and already using it on my private project.

However, we already use scalariform.
https://github.com/nulab/scala-oauth2-provider/blob/master/project/plugins.sbt

I'm not sure changing library is worth now.

**Comment by rmmeans** [comment]
I didn't even catch that scalariform was in the library. I guess I'm just used to what seems to be the more opinionated scalafmt. Thanks
