### ISSUE TITLE
value clientCredential is not a member

### ISSUE THREAD

**Issue by hieudo** [nulab/scala-oauth2-provider#113]
I have one bug when upgrade version "1.0.0" to latest version "1.1.0"
"value clientCredential is not a member of scalaoauth2.provider.AuthorizationRequest"

**Comment by tsuyoshizawa** [comment]
Thanks for the report.
I also just noticed the problem.

We changed the interface from 1.1.0.
In some cases, `AuthorizationHandler` uses validated client credential.

@rmmeans I created PR. Would you check?

**Comment by tsuyoshizawa** [comment]
I added `Option[ClientCredential]` argument to `validateClient` and `findUser` methods on `AuthorizationHandler`. Please use the parameter instead of `AuthorizationRequest#clientCredential` property.

I just released the fixed module as version 1.2.0.
