### ISSUE TITLE
AccessToken never expires

### ISSUE THREAD

**Issue by xring** [nulab/scala-oauth2-provider#118]
https://github.com/nulab/scala-oauth2-provider/blob/dbed51d3aa7f984ba0e8676297fe93718c7e80d7/src/main/scala/scalaoauth2/provider/DataHandler.scala#L23

the `expiresIn` will never change after initial.

**Comment by tsuyoshizawa** [comment]
The reason is from Avoid response where 'expiresIn' could be negative #107
The expires value will fix on creating `AccessToken` instance.

**Comment by xring** [comment]
Got it, that make sense. Thanks @tsuyoshizawa .
