### ISSUE TITLE
OpenID Connect

### ISSUE THREAD

**Issue by dstevenson** [nulab/scala-oauth2-provider#13]
With the recent launch of the final OpenID Connect 1.0 Specification, are there any plans to implement OpenID Connect on top of the OAuth2 provider in this library?

**Comment by lloydmeta** [comment]
:+1: Definitely interested in this.

@jclyons would you be able to share your improved implementation? It would be nice if we could get it to the point where it can be merged into scala-oauth2-provider or otherwise used as an added dependency easily.

**Comment by nafg** [comment]
+100, @dstevenson / @jclyons any chance of seeing a PR soon?

**Comment by nafg** [comment]
@tsuyoshizawa so how do you guys do authentication?

**Comment by tsuyoshizawa** [comment]
I use Authorization Code Grant and Client Credentials Grant to do authentication.

**Comment by nafg** [comment]
@tsuyoshizawa I don't understand. http://oauth.net/articles/authentication/ says

> OAuth 2.0 is not an authentication protocol.

You have to do _something_ on top of OAuth, like openid connect, no?

**Comment by tsuyoshizawa** [comment]
@nafg  My understanding was wrong about 'authentication'.

I am not going to implement OpenID Connect in our library.

**Comment by nafg** [comment]
@tsuyoshizawa ok, but I am curious what you guys do for authentication (meaning the application that consumes the API also wants to know "who" the user is), can you share?

**Comment by tsuyoshizawa** [comment]
@nafg  An generated access token (refresh token) and a user in database is just associated.

See my example. https://github.com/tsuyoshizawa/scala-oauth2-provider-example-skinny-orm

We can get a user data after authorized in controller.

**Comment by nafg** [comment]
So you basically have an api call "get user data" that returns some field
from the user associated with the oauth token, and you call it after the
user authorized himself?
