### ISSUE TITLE
Not able to find out the Main method, web server start code, endpoints(routes) code

### ISSUE THREAD

**Issue by Kuppusamy-oracle** [nulab/scala-oauth2-provider#135]
I am requesting you to provide these codes (Main method, web server start code, endpoints(routes) code, and curl command to run the project).

please give sample input requests and responses. It may help. 

Thanks

**Comment by tsuyoshizawa** [comment]
Here are sample projects. But the version is old, so please be careful.

- https://github.com/lglossman/scala-oauth2-deadbolt-redis
- https://github.com/tsuyoshizawa/scala-oauth2-provider-example-skinny-orm
