### ISSUE TITLE
Implicit grant type

### ISSUE THREAD

**Issue by Vadi** [nulab/scala-oauth2-provider#47]
Is there already [implicit grant type](https://tools.ietf.org/html/rfc6749#section-1.3.2) support or work around available? I can provide one if there is none already.

**Comment by gmalhi** [comment]
I was looking for this plugin is there pull request for implicit grant type now ? I am interested in it as well.

**Comment by tsuyoshizawa** [comment]
No, there isn't.
I don't get pull request.

**Comment by nafg** [comment]
@Vadi what happened with this?

**Comment by rmmeans** [comment]
So glad to see this! Thanks @satabin

**Comment by nafg** [comment]
The README needs to be updated
