### ISSUE TITLE
Why does OAuth2Provider::authorize not include error JSON in error response body

### ISSUE THREAD

**Issue by ctoomey** [nulab/scala-oauth2-provider#50]
OAuth2Provider:: issueAccessToken() and OAuth2Provider::authorize() handle errors mostly the same except that issueAccessToken() includes a JSON body describing the error and authorize() doesn't.  Is there a particular reason for not including the JSON body for authorize() errors?  If not I'll submit a pull request with that fixed.

**Comment by DStranger** [comment]
The spec does say that "the specifics of such error responses are beyond the scope of this specification". What's more important, different error responses for issuing token and accessing protected resources (header and body in one case and only header in the other) are forcing clients to use different logic when handling error responses.
I would say that we would only benefit from this.
