### ISSUE TITLE
How to refresh token

### ISSUE THREAD

**Issue by hxdhan** [nulab/scala-oauth2-provider#51]
Please tell me how to implement refresh token

**Comment by tsuyoshizawa** [comment]
Please see this project. It would be helpful to you.

https://github.com/oyediyildiz/scala-oauth2-provider-example

This example is written how to implement Refresh token by Play 2.2 and scala-oauth-provider 0.3.0. (old version)

**Comment by hxdhan** [comment]
yes , I got that example and I just got this router:
POST /oauth2/access_token controllers.OAuth2Controller.accessToken

do we need not a interface such as /oauth2/refresh_token  ?

**Comment by hxdhan** [comment]
yes , I got that example and I just got this router:
POST /oauth2/access_token controllers.OAuth2Controller.accessToken
I alse notice that OAuth2DataHandler have function refresh_token which only call create_token in that example. 
do we need not a interface just refresh token ?

**Comment by tsuyoshizawa** [comment]
No, we don't need to implement it for refresh token.
Just switch a ```grant_type``` parameter to ```refresh_token``` against ```/oauth2/access_token```.
Refresh token is also a way to issue an access token.

See documents (RFC) about OAuth 2.0.
