### ISSUE TITLE
How to use custom Grant Handlers

### ISSUE THREAD

**Issue by davidseth** [nulab/scala-oauth2-provider#52]
The README has a section on "Customizing Grant Handlers".  It has some code that says to create  a custom class MyTokenEndpoint which extends TokenEndpoint.  Where would I put this code and how would I reference/use it?

Essentially I want to set "clientCredentialRequired = false"

Thanks, David

**Comment by tsuyoshizawa** [comment]
Do you extends ```OAuth2Provider ``` of ```play2-oauth2-provider``` in your project?
Then you can override ```tokenEndpoint``` instance field to you implemented ```TokenEndPoint```.

https://github.com/nulab/scala-oauth2-provider/blob/master/play2-oauth2-provider/src/main/scala/scalaoauth2/provider/OAuth2Provider.scala#L16

**Comment by davidseth** [comment]
Perfect, Got it working in a few minutes. Awesome framework.
