### ISSUE TITLE
Post request with JSON body

### ISSUE THREAD

**Issue by liviuignat** [nulab/scala-oauth2-provider#62]
Hi,

It seems that if you try to post JSON to the server it does not work. I am looking at this code. It would be useful to parse JSON body also:

```
final def getParam[A](request: Request[A]): Map[String, Seq[String]] = {
    val form = request.body match {
      case body: play.api.mvc.AnyContent if body.asFormUrlEncoded.isDefined => body.asFormUrlEncoded.get
      case body: play.api.mvc.AnyContent if body.asMultipartFormData.isDefined => body.asMultipartFormData.get.asFormUrlEncoded
      case body: Map[_, _] => body.asInstanceOf[Map[String, Seq[String]]]
      case body: play.api.mvc.MultipartFormData[_] => body.asFormUrlEncoded
      case _ => Map.empty[String, Seq[String]]
    }

    form ++ request.queryString.map {
      case (k, v) => k -> (v ++ form.getOrElse(k, Nil))
    }
  }
```

**Comment by liviuignat** [comment]
getParam function is also final. I had to create my own OAuth2Provider and override implicit methods (it works until now):

```
trait MyOAuth2Provider extends OAuth2Provider {
  def getMyParam[A](request: Request[A]): Map[String, Seq[String]] = {
    request.body match {
      case body: play.api.mvc.AnyContentAsJson if body.asJson.isDefined => {
        body.asJson.get.as[JsObject].fields.toMap[String, JsValue].map{
          case (k, v) => k -> ArrayBuffer(v.as[String])
        }
      }
      case _ => getParam(request)
    }
  }

  override implicit def play2oauthRequest[A](request: Request[A]): AuthorizationRequest = {
    val param: Map[String, Seq[String]] = getMyParam(request)
    AuthorizationRequest(request.headers.toMap, param)
  }
}
```

Adding parsing of JSON body could be useful.

Cheers,

**Comment by tsuyoshizawa** [comment]
Thank for reporting.

I'm not sure how to just convert ```Map``` from ```Request``` is best in Play.
I couldn't find a method in Play, so I have copied a part of the logic.

Probably, this code would likely be the reference.
https://github.com/playframework/playframework/blob/2.3.x/framework/src/play/src/main/scala/play/api/data/Form.scala#L79-L85

I will fix this problem after confirm.

**Comment by tsuyoshizawa** [comment]
Fixed this problem.

I have published this updating as SNAPSHOT version.
Please check them.

I will release new version including this fix in few days.

**Comment by liviuignat** [comment]
Thanks will check it out.
