### ISSUE TITLE
Authorisation flow: Authorisation code destruction

### ISSUE THREAD

**Issue by lloydmeta** [nulab/scala-oauth2-provider#65]
Hi,

Firstly, great work on this lib; really helps a lot to have something like this to guide us in implementing a Scala Oauth2 provider :)

Cutting to the chase, it looks like this lib handles the generation of an AccessToken when provided an Authorisation Code. However, it doesn't seem to provide a way to ensure that once an AccessToken has been generated, the Authorisation code used gets destroyed, in order to ensure the following clause in [section 4.1.2 of the RFC](https://tools.ietf.org/html/rfc6749#section-4.1.2):

> The client MUST NOT use the authorization code more than once.  If an authorization code is used more than once, the authorization server MUST deny the request and SHOULD revoke (when possible) all tokens previously issued based on that authorization code.  The authorization code is bound to the client identifier and redirection URI.

I think one way is to add a `deleteAuthCode` method to `AuthorizationHandler`, and have `AuthorizationCode extends GrantHandler` call that upon successful completion of [`issueAccessToken `](https://github.com/nulab/scala-oauth2-provider/blob/master/scala-oauth2-core/src/main/scala/scalaoauth2/provider/GrantHandler.scala#L125)

Any thoughts?

**Comment by tsuyoshizawa** [comment]
> I think one way is to add a deleteAuthCode method to AuthorizationHandler, and have AuthorizationCode extends GrantHandler call that upon successful completion of issueAccessToken

We should implement this with your idea.
Could you send the PR to us?

**Comment by lloydmeta** [comment]
Definitely. Will send a PR :)

**Comment by tsuyoshizawa** [comment]
Thanks for your PR :+1:
