### ISSUE TITLE
Invalid sha1 on Maven

### ISSUE THREAD

**Issue by schmitch** [nulab/scala-oauth2-provider#67]
Currently thats what I get:
```
[warn] problem while downloading module descriptor: https://repo1.maven.org/maven2/com/nulab-inc/play2-oauth2-provider_2.11/0.15.0/play2-oauth2-provider_2.11-0.15.0.pom: invalid sha1: expected=a7f3dd2d7727011266328183c15e32af79f9c3d8 computed=01576f30fc55d27113d440651119d5392e2fab7a (404ms)
[warn] 	module not found: com.nulab-inc#play2-oauth2-provider_2.11;0.15.0
[warn] ==== local: tried
[warn]   /Users/schmitch/.ivy2/local/com.nulab-inc/play2-oauth2-provider_2.11/0.15.0/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/nulab-inc/play2-oauth2-provider_2.11/0.15.0/play2-oauth2-provider_2.11-0.15.0.pom
```

Actually I got this after clearing my Ivy2 cache ;)

**Comment by tsuyoshizawa** [comment]
I didn't know why we got this problem.
However, I've republished the version on maven central.
Now, it looks working fine.

Thanks.

**Comment by schmitch** [comment]
Thanks ;) <ironie>Maybe the NSA changed it ;) </ironie>

**Comment by tsuyoshizawa** [comment]
:alien:

**Comment by schmitch** [comment]
@tsuyoshizawa Just a small question which I ask here since its OT.
Is there a preferred SQL Layout for this repository? Currently I'm using it with a PostgreSQL, and I'm using tables that where generated with Django [auth_user, django_oauth2_provider] (I migrated away from it) However it looks really inperformant on login (subsequent logins via the token are really fast), but however I need like 4-6 or more queries to login (I only use password grant_type).

I mean I could easily reduce it to 3 but then my database gets filled pretty quickly with Tokens, however I also plan to add LDAP support, and currently It looks really hard to find a great fit into this library.

**Comment by tsuyoshizawa** [comment]
Have you checked some examples in written Readme?
[This example](https://github.com/tsuyoshizawa/scala-oauth2-provider-example-skinny-orm) may help you.

I never try using LDAP with this library, so I can't answer good way.
However, you can pass request parameter to `DataHandler` with instantiate.
The parameters would be useful in LDAP authentication.
