### ISSUE TITLE
Implicit Grant Type: Does not use validateClient per spec

### ISSUE THREAD

**Issue by rmmeans** [nulab/scala-oauth2-provider#73]
I don't think the Implicit grant type is really completed yet per OAuth Spec. Currently, you are required to implement the "validateClient" method, which checks a client Id and client secret. However, per the spec: http://tools.ietf.org/html/rfc6749#section-1.3.2 this is not valid. Implicit flows do not validate client secrets as implicit flows are used for things that can't be kept secret - like a Single Page App.

There is mention that you can validate the client identity - or at least that the request would be valid - if the client Id matches up properly with the registered redirect_uri.

**Comment by rmmeans** [comment]
I'm sorry.. this is a complete mental lapse. If that's how the spec requires to validate the client, then I would implement this in my own validateClient method as that method just returns a Future[Boolean].

However - it seems to me the real issue here is similar to what #71 is - if validateClient takes a AuthorizationRequest instead of a clientCredential type - then as an implicit type I could determine if the client id was valid based on the redirectUri that was included as part of the AuthorizationRequest.

Really - what is missing here is that the spec makes very careful mention that you should not validate and create a token on an implicit grant type for a client id unless the redirect uri that was provided matches a pattern of the redirectUri(s) that should have been provided at the time the client id was created by your provider.

**Comment by rmmeans** [comment]
@satabin -- I know you did the work on this implicit flow. Am I on the right page here? I think we are still missing a few pieces.

**Comment by tsuyoshizawa** [comment]
@rmmeans Thanks for the feedback. It really helps us.

I checked [an example request](https://bshaffer.github.io/oauth2-server-php-docs/grant-types/implicit/) from other oauth2-server implementation with Implicit grant.

The request parameter is very simple.
Implicit grant doesn't use client credentials in request.

> Currently, you are required to implement the "validateClient" method, which checks a client Id and client secret. However, per the spec: http://tools.ietf.org/html/rfc6749#section-1.3.2 this is not valid.

See [this logic](https://github.com/nulab/scala-oauth2-provider/blob/0.15.0/scala-oauth2-core/src/main/scala/scalaoauth2/provider/TokenEndpoint.scala#L22).

Implicit grant doesn't call `validateClient` without client credentials.
So [my this commit](https://github.com/nulab/scala-oauth2-provider/commit/97140bee2c01da75b37810fc79aab7bef54b66d1#diff-212a22f15d96ec166e921abdd45fa21bR47) was wrong.

However, [currently Implicit grant handler](https://github.com/nulab/scala-oauth2-provider/blob/520f5f062bec5304c77f17b5968f4ce0498191e1/scala-oauth2-core/src/main/scala/scalaoauth2/provider/GrantHandler.scala#L133) doesn't override `clientCredentialRequired` to change `false`.

https://github.com/nulab/scala-oauth2-provider/blob/0.15.0/scala-oauth2-core/src/main/scala/scalaoauth2/provider/TokenEndpoint.scala#L33

I think we need to override the method.
Then, Implicit grant will process to issue access token without `validateClient`.

Do we need just client_id and redirect_uri to get user for Implicit grant?
It is easy to understand what we should use parameters for Implicit grant.

**Comment by satabin** [comment]
As far as I can see in the RFC, only `client_id` and `redirect_url` are required. The rest is optional.

**Comment by satabin** [comment]
@rmmeans This is a first version which requires improvements for sure. Thanks for the feedback.

@tsuyoshizawa Do you want me to look into it?

**Comment by tsuyoshizawa** [comment]
> As far as I can see in the RFC, only client_id and redirect_url are required. The rest is optional.

Yes. Password grant is same too (username and password are required). So I thought I want to change findUser method.

**Comment by rmmeans** [comment]
I've been spending a little time digging into this project again -- it's been almost a year since I last touched it. 

Upon review - especially with the good work that @satabin has done to get the implicit grant working I'm wondering if a larger refactor is needed. Here's what I'm questioning:

* We are at a junction where in order to properly call several of the methods on the AuthorizationHandler trait that we have to overload them for two versions of the same method - one that takes specific values and one that takes the AuthorizationRequest it self (i.e. `findUser(username: String, password: String)` and `def findUser(request: AuthorizationRequest)`
* Looking at the AuthorizationRequest case class, I'm finding my self questioning it's current implementation - if this thing is going to have methods such as `def clientId: Option[String]` then in my opinion, as a user of this class, it should retrieve an Option[String] for the clientId regardless if the client id was in the request body or in the Authorization Header. It shouldn't only be able to retrieve it from the body params... it 
* **If** the AuthorizationRequest's object's methods could work regardless if it was a header value or a body value, then the methods in the AuthorizationHandler trait only need to receive the authorization request object. The user who implements that method in their custom data handler will have easy access to the various values regardless of their origin. What I'm really suggesting is that the following methods could be replaced with methods that only take a `request: AuthorizationRequest`: 
 * `def validateClient(clientCredential: ClientCredential, grantType: String)`
 * `def findUser(username: String, password: String)`
 * `def findClientUser(clientCredential: ClientCredential, scope: Option[String])`

By doing this - it gives the best flexibility to the implementor on the specifics of each grant type as of the params are easily available via the methods on the AuthorizationRequest object regardless of their origin -- and by doing this, it will make working with the implicit grant flow much simpler.




@tsuyoshizawa on your comment above, I think `clientCredentialRequired` is requried - but what you are really validating is that the client Id and redirect URI are valid... which, if implemented in terms of what I described above would put that implementation of how to validate it on the implementor of the trait for the  * `def validateClient(request: AuthorizationRequest)` method.

**Comment by tsuyoshizawa** [comment]
@rmmeans Thanks for the detail comment.
I could understand what your point is.

> if implemented in terms of what I described above would put that implementation of how to validate it on the implementor of the trait for the * def validateClient(request: AuthorizationRequest) method.

Parsed `ClientCredential` just use client_id and client_secret.
If the change give us a more simplicity interface, then it is welcome.

**Comment by rmmeans** [comment]
Cool. I've been starting to do some refactoring work on this - but didn't want to spend too much time on it. I'll start working on some PR's and we can start getting some feedback.

**Comment by rmmeans** [comment]
@satabin I know I said I would put some PR's together, but I've ran out of time and no longer need implicit flow. I'd be glad to give feedback though on any other improvements to the implicit flow if somebody else wants to tackle it!

**Comment by satabin** [comment]
I haven't had much time lately to work on this. I am also working on integration within spray in addition to play, and may I may discover some other required refactoring. Let's see what will happen on this front.

**Comment by rmmeans** [comment]
That's awesome! Just letting you know to not wait on me since I don't need implicit grant any longer.

**Comment by damirv** [comment]
I could give it a try but I'm not sure if we reached some consensus here. @tsuyoshizawa Let me know if I can do something for this issue.
