### ISSUE TITLE
published jar 0.15.1 incorrect?

### ISSUE THREAD

**Issue by damirv** [nulab/scala-oauth2-provider#75]
It seems that the 0.15.1 version is missing completely these commits:
https://github.com/nulab/scala-oauth2-provider/commit/f183a31e3c2bb8cf92dfe58753f5a7e638300ea9
https://github.com/nulab/scala-oauth2-provider/commit/97140bee2c01da75b37810fc79aab7bef54b66d1

Can you verify that published the correct jars?

Thanks

**Comment by damirv** [comment]
Never mind, I see that those commits are on the master branch. Any idea when you want to release those?

**Comment by tsuyoshizawa** [comment]
We talked about improving library's interface at #73.
But they and I don't have time now, but I want to release after improve the interface.

For now, I uploaded snapshot version as 0.16.0-SNAPSHOT.
Please try the version, if you want to use the feature now.

**Comment by tsuyoshizawa** [comment]
@damirv I just released version 0.16.0. Please check it. Thank you.
