### ISSUE TITLE
[Question] Spray.io example ?

### ISSUE THREAD

**Issue by hajime-moto** [nulab/scala-oauth2-provider#81]
Hi,

First of all thank you for this awesome library :)

Is there an example on how to use scala-oauth2-provider with spray or just without Play ?

**Comment by tsuyoshizawa** [comment]
There is no example as official.

However, I saw a commit previously to support Spray.io. https://github.com/gnieh/scala-oauth2-provider/commit/24cc36ec74bd426ad5f0c61c310dfe114277c514

It might help you.
