### ISSUE TITLE
Customize access to an authorized resource using Action Composition

### ISSUE THREAD

**Issue by harmeetsingh0013** [nulab/scala-oauth2-provider#92]
Hello Team,

I have requirement for manage Token authentication according to User Domain. The domain we found using `request` object in action composition. By Using scala Oauth, we are using following ling of code in our request handler like 

```
def testCustomAction = Action.async { implicit request =>
    request.headers.get("Host").map { host =>
      authorize(new SecurityDataHandler(host)) { authInfo =>
        Future.successful(Ok("Go and Run"))
      }
    } getOrElse {
      Future.successful(Unauthorized("401 No user\n"))
    }
  }
```

In above code, we are repeating `request.headers.get("Host").map { host => authorize(new SecurityDataHandler(host)) { authInfo => ` lines of code into our every handler, but i want to create our custom command handler by using Oauth security. I am trying to create custom handler using following code:

```
class CustomSecurityAction[A](action: Action[A]) extends Action[A] with OAuth2Provider{
  
  def apply(request: Request[A]): Future[Result] = {
    request.headers.get("Host").map { host =>
      authorize(new SecurityDataHandler(host)) { authInfo =>
        Future.successful(Ok("Go and Run"))
      }
    } getOrElse {
      Future.successful(Unauthorized("401 No user\n"))
    }
  }

  lazy val parser = action.parser
}
```

But above code give me following error: 

```
◾Cannot find any HTTP Request here
◾not enough arguments for method authorize: (implicit request: play.api.mvc.Request[Any], implicit ctx: scala.concurrent.ExecutionContext)scala.concurrent.Future[play.api.mvc.Result]. Unspecified value parameters request, ctx.
```

How can i do this?

**Comment by tsuyoshizawa** [comment]
You could pass `RequestHeader` and `ExecutionContext` object directly to `authorize` method.
Please check `authorize` method definition.

```
class CustomSecurityAction[A](action: Action[A]) extends Action[A] with OAuth2Provider{

  def apply(request: Request[A]): Future[Result] = {
    request.headers.get("Host").map { host =>
      authorize(new SecurityDataHandler(host)) { authInfo =>
        Future.successful(Ok("Go and Run"))
      }(request ,play.api.libs.concurrent.defaultContext)
    } getOrElse {
      Future.successful(Unauthorized("401 No user\n"))
    }
  }

  lazy val parser = action.parser
}
```

BTW, I think you could validate in DataHandler `host` parameter by passing request object to `DataHandler`.

```
new SecurityDataHandler(request)
```

```
class SecurityDataHandler(playRequest: Request) {
  override def validateClient(request: AuthorizationRequest): Future[Boolean] = {
    playRequest.headers.get("Host").map { host =>
      // validation
    }.getOrElse(Future.successful(false))
  }
```

Then, you don't need to create custom Action for only this.

**Comment by harmeetsingh0013** [comment]
Hello tsuyoshizawa,

Thank You, i found the solution and thanks for your help. I really missed the `RequestHeader` and `ExecutionContext` object. Now its working fine. 

I am not able to pass `request` into our `SecurityDataHandler` because i am using `AuthorizedAction(new SecurityDataHandler)` for managing security and at that time, our request object is not available. Otherwise we need to  use `authorize` block in every handler and repeat the code. [Please click on link, for my customize security handler.](http://stackoverflow.com/questions/37873343/play-framework-2-3-x-wrap-request-object-using-scala-oauth-in-play-framework/37878749#37878749)

**Comment by tsuyoshizawa** [comment]
I understand your case.

> Now its working fine.

 I'm glad to hear that. I close this issue.

**Comment by harmeetsingh0013** [comment]
Thanks tsuyoshizawa for your help.
