### ISSUE TITLE
akka-http-oauth2-provider miss a way to extend the AccessToken response

### ISSUE THREAD

**Issue by chpache** [nulab/scala-oauth2-provider#99]
Would be great, just as in scalaoauth2.provider.OAuth2Provider from play2-oauth2-provider, to be able to extend the response with other data. 

Just as the scalaoauth2.provider.OAuth2Provider.responseAccessToken. It might also just use the default json formatter but it would be great to be able to override it.

**Comment by tsuyoshizawa** [comment]
Thanks for the PR.
